# 04 - Filtering - Using Conditionals to Filter Rows and Columns 

https://youtu.be/Lw2rlcxScZY?si=GV9Pm1IzeNSndh-p

Notes by [Innovinitylabs](https://github.com/innovinitylabs)

In [2]:
import pandas as pd
people = {
    "first": ["Corey", 'Jane', 'John'], 
    "last": ["Schafer", 'Doe', 'Doe'], 
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com']
}
dft = pd.DataFrame(people)

to get everyone with last name Doe

we get only a `series` with yes or no

In [3]:
dft['last'] == 'Doe'

0    False
1     True
2     True
Name: last, dtype: bool

so we are adding it to a variable for clarity and then later we can use it to filter and get the data we need

In [4]:
filt = (dft['last'] == 'Doe') # () added for clarity

In [28]:
filt

0    False
1     True
2     True
Name: last, dtype: bool

we can put it directly in the brackets for dataframe  but for clarity we are adding it variable and use

In [5]:
dft[filt]

  first last              email
1  Jane  Doe  JaneDoe@email.com
2  John  Doe  JohnDoe@email.com

but its better to use `.loc` since we can also filter using column if needed

In [6]:
dft.loc[filt, 'email']

1    JaneDoe@email.com
2    JohnDoe@email.com
Name: email, dtype: object

#### AND OR Operator in pandas
> AND = `&`  
> OR  = `|`

In [7]:
filt2 = (dft['last'] == 'Doe') & (dft['first'] == 'John')

In [9]:
dft.loc[filt2, 'email']

2    JohnDoe@email.com
Name: email, dtype: object

to negate the filter we use `~` (kinda like NOT)

In [10]:
dft.loc[~filt2, 'email']

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
Name: email, dtype: object

### Survey Data

In [11]:
df = pd.read_csv('data/survey_results_public.csv', index_col='Respondent' )
schema_df = pd.read_csv('data/survey_results_schema.csv', index_col='Column')
pd.set_option('display.max_columns', 85)

In [ ]:
# pd.set_option('display.max_rows', 85)

In [14]:
df.head(1)

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult

In [16]:
schema_df

                                                   QuestionText
Column
Respondent    Randomized respondent ID number (not in order ...
MainBranch    Which of the following options best describes ...
Hobbyist                                Do you code as a hobby?
OpenSourcer         How often do you contribute to open source?
OpenSource    How do you feel about the quality of open sour...
...                                                         ...
Sexuality     Which of the following do you currently identi...
Ethnicity     Which of the following do you identify as? Ple...
Dependents    Do you have any dependents (e.g., children, el...
SurveyLength  How do you feel about the length of the survey...
SurveyEase    How easy or difficult was this survey to compl...

[85 rows x 1 columns]

To filter high salary and know what languages they know

In [18]:
filt_highsal = (df['ConvertedComp'] > 70000)

In [20]:
df.loc[filt_highsal, ['Country', 'LanguageWorkedWith', 'ConvertedComp']]

,Country,LanguageWorkedWith,ConvertedComp
Respondent,,,
6,Canada,Java;R;SQL,366420.0
9,New Zealand,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;P...,95179.0
13,United States,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...,90000.0
16,United Kingdom,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;T...,455352.0
22,United States,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...,103000.0
...,...,...,...
88876,United States,Bash/Shell/PowerShell;C#;HTML/CSS;Java;Python;...,180000.0
88877,United States,Bash/Shell/PowerShell;C;Clojure;HTML/CSS;Java;...,2000000.0
88878,United States,HTML/CSS;JavaScript;Scala;TypeScript,130000.0
88879,Finland,Bash/Shell/PowerShell;C++;Python,82488.0
88882,Netherlands,C#;HTML/CSS;Java;JavaScript;PHP;Python,588012.0

In [22]:
countries = ['India', 'Germany']
country_filt = df['Country'].isin(countries)

In [25]:
# df[country_filt, ['LanguageWorkedWith', 'ConvertedComp'] ] this gives error
df.loc[country_filt, ['LanguageWorkedWith', 'ConvertedComp'] ]

                                           LanguageWorkedWith  ConvertedComp
Respondent
8           Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...            NaN
10                              C#;Go;JavaScript;Python;R;SQL        13293.0
14                                                        C++        57060.0
15          Assembly;Bash/Shell/PowerShell;C;C++;HTML/CSS;...            NaN
36                                         Java;Kotlin;Python        20628.0
...                                                       ...            ...
80319       Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...            NaN
83786                   HTML/CSS;JavaScript;Kotlin;TypeScript            NaN
83862       Assembly;C;C++;HTML/CSS;Java;JavaScript;Object...            NaN
84299        HTML/CSS;Java;JavaScript;Python;Swift;TypeScript            NaN
86012           Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript            NaN

[14927 rows x 2 columns]

#### String Methods Basics

language filter

In [26]:
lang_filt = df['LanguageWorkedWith'].str.contains('Python', na=False)

we can use `.str.contains()` and give `na=False` for those columns that contains no values

In [27]:
df.loc[lang_filt, ['LanguageWorkedWith', 'ConvertedComp']]

                                           LanguageWorkedWith  ConvertedComp
Respondent
1                             HTML/CSS;Java;JavaScript;Python            NaN
2                                         C++;HTML/CSS;Python            NaN
4                                         C;C++;C#;Python;SQL        61000.0
5                 C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA            NaN
8           Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...            NaN
...                                                       ...            ...
84539       Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...            NaN
85738         Bash/Shell/PowerShell;C++;Python;Ruby;Other(s):            NaN
86566         Bash/Shell/PowerShell;HTML/CSS;Python;Other(s):            NaN
87739                C;C++;HTML/CSS;JavaScript;PHP;Python;SQL            NaN
88212                              HTML/CSS;JavaScript;Python            NaN

[36443 rows x 2 columns]